# Generated by Django 6.0.1 on 2026-02-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_remove_address_created_at_address_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
